# Generated by Django 5.1 on 2024-08-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_alter_blog_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
